version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: moving-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fs2_part4_team3_be
      POSTGRES_DB: moving_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moving-nestjs
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: fs2_part4_team3_be
      DATABASE_NAME: moving_db
      DATABASE_URL: postgresql://postgres:fs2_part4_team3_be@postgres:5432/moving_db?schema=public
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nestjs

volumes:
  postgres_data:
